test: write snapshot tests - send user message
sendbird/chat-ai-widget pull request #381
Opened 2024-10-25 03:59 UTC by liamcho

## Changes
- 

ticket: []

## Additional Notes
- 

## Checklist
Before requesting a code review, please check the following:
- [ ] **[Required]** CI has passed all checks.
- [ ] **[Required]** A self-review has been conducted to ensure there are no minor mistakes.
- [ ] **[Required]** Unnecessary comments/debugging code have been removed.
- [ ] **[Required]** All requirements specified in the ticket have been accurately implemented.
- [ ] Ensure the ticket has been updated with the sprint, status, and story points.

2024-11-11 01:33 UTC, bang9 commented on .circleci/config.yml
> -            # - packages/uikit/node_modules --> submodules are not cached
요거는 놔둬주실 수 있을까요?

2024-11-11 01:40 UTC, liamcho commented on package.json
> +  "private": true,
<img width="811" alt="Screenshot 2024-11-11 at 10 39 50 AM" src="https://github.com/user-attachments/assets/d213f4ce-09e4-46f7-a4c2-64fb47108c88">

2024-11-11 01:41 UTC, liamcho commented on playwright.config.ts
> +  workers: undefined, // process.env.CI ? 1 : undefined,
undefined allows using maximum possible number of workers

2024-11-11 01:42 UTC, liamcho commented on src/const.ts
> +  enableMessageGrouping: boolean;
need this for snapshot test to produce same results that are not based on current time.

2024-11-11 01:44 UTC, liamcho commented on tsconfig.json
> +    "__visual_tests__",
so tsconfig is applied to snapshot test files.

2024-11-11 01:46 UTC, liamcho commented on .circleci/config.yml
> -            # - packages/uikit/node_modules --> submodules are not cached
넵 실수로 지워진것 같습니다. 돌려 놓았습니다.

2024-11-11 01:52 UTC, bang9 requested changes

2024-11-11 01:52 UTC, bang9 commented on .yarnrc.yml
> +
요건 어떤것때문에 추가 된걸까용?

2024-11-11 01:52 UTC, bang9 commented on __visual_tests__/utils.ts
> +}
특정 element 가 보여지기를 기다린다거나, 특정 상태가 되기를 기다려야 할때는 `waitFor({ state })` 를 사용하면 좋을 것 같습니다.
https://playwright.dev/docs/api/class-locator#locator-wait-for

1. 페이지를 이동하고, 위젯 버튼이 나타나기를 기다리는 상황
2. 위젯 버튼을 클릭하고, 채팅창이 나타나기를 기다리는 상황

2024-11-11 01:52 UTC, bang9 commented on __visual_tests__/utils.ts
> +export async function assertScreenshot(page: Page, screenshotName: string, browserName: string) {
Q. 혹시 arch(os) 도 넣는건 어떨까요?

2024-11-11 01:52 UTC, bang9 commented on package.json
> +  "private": true,
요거는 왜 추가된걸까요? 저희 패키지 배포해야해서 Private 추가되면 안될 것 같아용

2024-11-11 01:52 UTC, bang9 commented on src/main.tsx
> +  }
이름을 ci 혹은 snapshot, mode='snapshot' 뭐 이런거로 바꾸는건 어떨까요?
아래쪽을 보니 disableTimestamps 를 가지고 stringSet, message grouping 을 같이 핸들링하고 있어서요
테스트만을 위해 추가된 플래그이니, 여기서는 테스트 모드라는게 명시되면 좋을 것 같아요

2024-11-11 01:54 UTC, bang9 commented on .circleci/config.yml
> +            yarn install
삭제 및 재설치는 왜 진행하는걸까요?

2024-11-11 02:03 UTC, bang9 commented on package.json
> +  "private": true,
경험하신 에러는 corepack 활성화가 안되어서, yarn v1 으로 실행이 되면서 발생하는 것 같아 보여요

2024-11-11 02:07 UTC, liamcho commented on package.json
> +  "private": true,
아 private이면 배포가 안되는군요. 다른 방법을 찾아보겠습니다.

2024-11-11 02:27 UTC, liamcho commented on src/main.tsx
> +  }
넵 동의합니다. 수정했습니다

2024-11-11 02:29 UTC, liamcho commented on package.json
> +  "private": true,
음 corepack enable step 을 추가했는데도 실패하네요
- https://app.circleci.com/pipelines/github/sendbird/chat-ai-widget/2223/workflows/cc04b813-b186-4409-b5a0-776e1d9eb8fd/jobs/3097
- https://github.com/sendbird/chat-ai-widget/commit/477bd2a0e24db4a833a4b26c337f35fb5d2118c4

2024-11-11 04:31 UTC, bang9 commented on package.json
> +  "private": true,
corepack 이 정상적으로 활성화가 안된거 아닐까요?

2024-11-11 05:05 UTC, liamcho commented on .yarnrc.yml
> +
이것저것 실험하면서 들어간거 같은데 필요한 이유는 없어보여서 지우는게 좋겠습니다.

2024-11-11 05:34 UTC, liamcho commented on .circleci/config.yml
> +            yarn install
저도 어떻게 들어갔는지 모르겠네요. 필요없는 코드 같아서 지웠습니다.

2024-11-11 06:28 UTC, liamcho commented on package.json
> +  "private": true,
완료요!

2024-11-11 06:28 UTC, liamcho commented on .yarnrc.yml
> +
완료요!

2024-11-11 06:28 UTC, liamcho commented on __visual_tests__/utils.ts
> +}
완료요!

2024-11-11 06:28 UTC, liamcho commented on __visual_tests__/utils.ts
> +export async function assertScreenshot(page: Page, screenshotName: string, browserName: string) {
완료요!

2024-11-11 06:28 UTC, liamcho commented on package.json
> +  "private": true,
완료요!

2024-11-11 07:00 UTC, bang9 commented on .circleci/config.yml
> +          command: corepack enable --install-directory ~/bin
불필요한 스텝도 조금 끼어있고, linux 를 위해 추가한 커맨드가 macos 에서 사용되고 좀 섞여있어서요

CI 구성에서 각 항목이 어떤 역할을 하는지 문서와 예제를 보신 뒤에
전체적인 CI 구성이나 흐름을 한번 다듬으면 좋을 것 같습니다.

- [commands](https://circleci.com/docs/configuration-reference/#commands)
- [attach_workspace](https://circleci.com/docs/configuration-reference/#attachworkspace)
- [persist_to_workspace](https://circleci.com/docs/configuration-reference/#persisttoworkspace)

2024-11-11 07:23 UTC, bang9 commented on .circleci/config.yml
> +          command: find /Users/distiller/project/__visual_tests__ -type f
이건 제거해도 괜찮나용?

2024-11-11 07:24 UTC, bang9 commented on src/main.tsx
> +  }
수정이 안된거같습니다

2024-11-11 07:27 UTC, bang9 commented on __visual_tests__/workflow-tests.spec.ts
> +  await page.waitForTimeout(2500);
이거도 waitFor 사용해서, 위젯 버튼이 나타나는걸 기다리도록 변경 가능할까요?

2024-11-11 07:35 UTC, liamcho commented on .circleci/config.yml
> +          command: find /Users/distiller/project/__visual_tests__ -type f
넵 디버깅 용도라 지우겠습니다.

2024-11-11 07:35 UTC, liamcho commented on __visual_tests__/workflow-tests.spec.ts
> +  await page.waitForTimeout(2500);
넵

2024-11-11 07:39 UTC, bang9 commented on __visual_tests__/utils.ts
> +  const name = `${screenshotName}.${browserName}.${arch}.png`; // Include the browser and OS architecture info in the filename
![image](https://github.com/user-attachments/assets/827abd4b-2791-4e85-ab5c-5fd753ba3b18)
playwright 에서는 process.platform 사용한다고 하네요
```suggestion
import {expect, Page} from "@playwright/test";

import {WidgetComponentIds} from "./const";

export async function assertScreenshot(page: Page, screenshotName: string, browserName: string) {
  const name = `${screenshotName}.${browserName}.${process.platform}.png`; // Include the browser and OS architecture info in the filename
```

2024-11-11 07:42 UTC, bang9 commented on .circleci/config.yml
> +          command: yarn playwright install
https://playwright.dev/docs/ci-intro
문서를 보면 `npx playwright install --with-deps` 로 충분한가봐요~

2024-11-13 02:00 UTC, liamcho commented on src/main.tsx
> +  }
엥? 다시 확인해보겠습니다..

2024-11-13 04:12 UTC, liamcho commented on src/main.tsx
> +  }
다시 작업해서 커밋했습니다.

2024-11-13 04:12 UTC, liamcho commented on .circleci/config.yml
> +          command: find /Users/distiller/project/__visual_tests__ -type f
완료요!

2024-11-13 04:13 UTC, liamcho commented on __visual_tests__/workflow-tests.spec.ts
> +  await page.waitForTimeout(2500);
완료요!

2024-11-13 04:13 UTC, liamcho commented on .circleci/config.yml
> +          command: yarn playwright install
넵 감사합니다 수정 완료요!

2024-11-13 05:37 UTC, bang9 commented on src/main.tsx
> +  }
```suggestion
  const isSnapshot = urlParams.get('snapshot') === 'true';
```

2024-11-13 05:40 UTC, bang9 commented on src/utils/messages.ts
> +  enableMessageGrouping: boolean,
요거 파라메터가 마지막으로 들어가는게 자연스럽지 않을까요?

enableMessageGrouping = true

2024-11-13 05:55 UTC, liamcho commented on src/utils/messages.ts
> +  enableMessageGrouping: boolean,
prev next 가 둘다 optional 이라 괜찮을까요?

2024-11-13 06:06 UTC, bang9 commented on src/utils/messages.ts
> +  enableMessageGrouping: boolean,
넵 enableMessageGrouping 도 옵셔널 + 기본값 true 로 넣으면 될거같아요

2024-11-13 06:12 UTC, bang9 commented on .circleci/config.yml
> +          destination: playwright-test-results
요거 언제 롤백된건지 모르겠지만, 다시 코멘트 남깁니다
https://circleci.com/docs/collect-test-data/#playwright

2024-11-13 06:15 UTC, bang9 commented on __visual_tests__/const.ts
__visual_tests__ 디렉토리에도 eslint 와 prettier 적용할 수 있을까요?

2024-11-13 06:22 UTC, liamcho commented on .circleci/config.yml
> +          destination: playwright-test-results
수정했습니다

2024-11-13 06:24 UTC, liamcho commented on src/utils/messages.ts
> +  enableMessageGrouping: boolean,
수정했습니다

2024-11-13 06:58 UTC, bang9 commented on .circleci/config.yml
> +          destination: playwright-test-results
store_artifacts 를 store_test_results 로 ! 변경을 한번 해보시쥬

2024-11-13 06:59 UTC, liamcho commented on __visual_tests__/const.ts
완료요!

2024-11-13 07:00 UTC, liamcho commented on .circleci/config.yml
> +          destination: playwright-test-results
넵 완료요!

2024-11-13 08:12 UTC, bang9 commented on .circleci/config.yml
> +          destination: playwright-test-results
![image](https://github.com/user-attachments/assets/53032dac-df76-4891-bec3-84fd339c8e3f)

테스트 결과 파일이 어디에 나오는지 확인하고, 그곳으로 경로 변경이 필요해 보입니다용

2024-11-14 02:17 UTC, liamcho commented on .circleci/config.yml
> +          destination: playwright-test-results
[완료요!](https://app.circleci.com/pipelines/github/sendbird/chat-ai-widget/2322/workflows/fb932e81-640b-4ec8-be6a-664db20e437b/jobs/3549/tests).

2024-11-14 03:05 UTC, bang9 commented on .circleci/config.yml
> +          at: /Users/distiller/project
```suggestion
```

2024-11-14 03:05 UTC, bang9 commented on .circleci/config.yml
> +          path: /Users/distiller/project/test-results
```suggestion
          path: ~/project/test-results
```

2024-11-14 03:05 UTC, bang9 commented on .circleci/config.yml
> +          path: /Users/distiller/project/playwright-report
```suggestion
          path: ~/project/playwright-report
```

2024-11-14 03:06 UTC, bang9 approved these changes
lgtm!

2024-11-14 05:54 UTC, merged